name: fancywork
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # redux: ^5.0.0

  get_it: ^7.1.3
  flutter_bloc: ^7.0.0
  # built_collection: ^5.0.0
  # built_value: ^8.0.6
  device_info: ^2.0.0
  freezed_annotation: ^0.14.2
  logger: ^1.0.0
  provider: ^5.0.0
  rxdart: ^0.27.1
  # built_redux: ^8.0.0

  # design:
  #   path: ../design
  # flutter_built_redux:
  #   git:
  #     url: https://github.com/ligastavok/flutter_built_redux.git
  #     ref: v3.x

  # design_system:
  #   path: ../design_system

  # custom packages
  utils:
    path: ./packages/utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  built_value_generator: ^8.0.6
  build: ^2.0.0
  freezed: ^0.14.2
  pedantic: ^1.11.0

dependency_overrides:
  meta: 1.3.0 # caused by flutter_test from sdk
  test_api: ^0.4.0 # caused by flutter_test from sdk

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/theme/

flutter_intl:
  enabled: false # Disable when push
  main_locale: ru
  arb_dir: lib/src/l10n
  output_dir: lib/src/generated
  class_name: FancyworkIntl