name: domain
description: domain
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  redux: ^5.0.0
  freezed_annotation: ^0.14.2
  json_serializable: ^4.1.3

dev_dependencies:
  freezed: ^0.14.2
  build_runner: ^2.0.4
  build: ^2.0.0
  pedantic: ^1.11.0
  test: ^1.17.9